name       : libmanette
version    : 0.2.2
release    : 2
source     :
    - https://download.gnome.org/sources/libmanette/0.2/libmanette-0.2.2.tar.xz : 8b1b9fbaf84f1e383141a5715a2494f507e62313721ad993c39a868fc5ccf7d2
license    : LGPL-2.1-only
component  : programming.library
summary    : libmanette is a small GObject library giving you simple access to game controllers.
description: |
    libmanette is a small GObject library giving you simple access to game controllers. This library is intended for software needing a painless access to game controllers from any programming language and with little dependencies.
builddeps  :
    - pkgconfig(gio-2.0)
    - pkgconfig(libevdev)
    - valadoc
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
