name       : libmanette
version    : 0.2.3
release    : 3
source     :
    - https://download.gnome.org/sources/libmanette/0.2/libmanette-0.2.3.tar.xz : c0f065155ae64ceda7a880536878685aeeee4c55fd17aaea8ef0bc2fac3cb0ff
license    : LGPL-2.1-only
component  : programming.library
summary    : libmanette is a small GObject library giving you simple access to game controllers.
description: |
    libmanette is a small GObject library giving you simple access to game controllers. This library is intended for software needing a painless access to game controllers from any programming language and with little dependencies.
builddeps  :
    - pkgconfig(gio-2.0)
    - pkgconfig(libevdev)
    - valadoc
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
