name       : libmanette
version    : 0.2.4
release    : 5
source     :
    - https://download.gnome.org/sources/libmanette/0.2/libmanette-0.2.4.tar.xz : 4fe0a4bed6b4c3ae7249d341031c27b32f8d9e0ffb5337d71cbcec7160362cf7
license    : LGPL-2.1-only
component  : programming.library
summary    : libmanette is a small GObject library giving you simple access to game controllers.
description: |
    libmanette is a small GObject library giving you simple access to game controllers. This library is intended for software needing a painless access to game controllers from any programming language and with little dependencies.
builddeps  :
    - pkgconfig(gio-2.0)
    - pkgconfig(libevdev)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
