name       : libmanette
version    : 0.2.0
release    : 1
source     :
    - https://download.gnome.org/sources/libmanette/0.2/libmanette-0.2.0.tar.xz : af9e59b8d9ab792391a229c2824cac99740676785fdd460588fe9f5a05e613ff
license    : LGPL-2.1-only
component  : programming.library
summary    : libmanette is a small GObject library giving you simple access to game controllers.
description: |
    libmanette is a small GObject library giving you simple access to game controllers. This library is intended for software needing a painless access to game controllers from any programming language and with little dependencies.
builddeps  :
    - pkgconfig(gio-2.0)
    - pkgconfig(libevdev)
    - valadoc
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
